SELECT t.CITY, t.len
FROM (
SELECT CITY, LENGTH(CITY) as len , RANK() OVER (PARTITION BY LENGTH(CITY) ORDER BY CITY ASC) as r
FROM STATION
WHERE
LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION) or
LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION)
) as t
where t.r = 1
ORDER BY len desc